### ISSUE TITLE
Problem 4.2 minimization strategy VBA assigement

### ISSUE THREAD

**Issue by au201805** [bss-osca/tfa#3]
Hello 
I think we are many students who is struggling with problem "4.2", especially the CalcFreeSlots function and how to formulate it. Could you point us in the right direction for where to begin?

**Comment by JesperBangMikkelsen** [comment]
Hi,
You would need to loop through the free spots before and after the current request you are trying to assign to a seat. 

The CalcFreeSlots function is intended to be used for counting the number of seats before and after the current requests you are trying to place. In order to do this, you would need to perform the following steps (among others):
1. Check if a seat is free for the entire trip of a request before.
2. If a seat is available for the entire trip, then the CalcFreeSlots will be called and do the following:
   - Count the number of seats **after** the final station of the request by looping through all seats from s2 until you reach the first request placed in that seat after the current request. Consider "Exit For" to break the loop at the right time and stop the counter when you have found the request placed after the current request.
   - Count the number of seat **before** the first station of the request by looping through all seats from s1 until you reach the request placed before the current request in that seat. You can consider "Step -1" in your loop to loop backwards (try to google this) and "Exit For" to break the loop at the right time.
   - Have CalcFreeSlots return the total number of seats before and after, that you have just found through the counts in the above loops. 
3. Finally, you should in your overall program have some kind of mechanism that checks whether the overall seat count returned by CalcFreeSlots is lower than the current best. You can have a look at the "Job Sequencing" assignment a few weeks back for inspiration. 

Br.
Jesper
